### PR TITLE
feat(Enumerable): Support choose values from sequence of options

### PR DESCRIPTION
**Pull request by skarllot**
Chooses values from a sequence of options where the option has a value, optionally applies a selector function to each value and returns the results.

### CODE REVIEW

**Comment by jeffijoe** [comment]
Thanks for the PR @skarllot!

There's already a `.Somes()` which will filter all the `Some`s from a `IEnumerable<Option<T>>` - `Choose` would be a `Somes` + `Map`.

Do you think it's still worth adding this over composing `Somes` and `Map`?

**Comment by skarllot** [comment]
Sorry, I've missed `Somes` method. But I have two points:
- Maybe should create an overload to define a mapper;
- I don't think that it should materialize to a list, should return an enumerable.

**Comment by jeffijoe** [comment]
I've got mixed feelings on both points.

> Maybe should create an overload to define a mapper;

My initial gut reaction is "just compose `Somes` + `Map`, FP embraces composition", but on the other, `Sequence` is often provided as a shorthand for `Traverse(x => x)`, so I think we can add an overload with a selector. I'd just be concerned that the name `Choose` wouldn't convey the meaning of what it does, and `Somes(x => .Property)` also feels a bit weird.

> I don't think that it should materialize to a list, should return an enumerable.

We purposely have been using `IReadOnlyList` as the default list interface because in practice, more often than not we would get a `Possible multiple enumeration﻿` warning and would then have to enumerate to a temporary variable. Also, for certain operations like `Map`, we can pre-allocate a list with a known size ahead of time.

On the other hand, as I assume is your point, this does mean using eager evaluation which may also not be desirable. In those cases, what we've done is define 2 overloads, one that accepts and returns `IEnumerable` and one that accepts and returns `IReadOnlyList`. The compiler will choose the more specialized one, so we get the benefit of both.

For `Somes`, this could be done like:

* `IEnumerable<U> Somes<T, U>(this IEnumerable<Option<T>> source)` 
* `IReadOnlyList<U> Somes<T, U>(this IReadOnlyList<Option<T>> source)`

Thoughts?

**Comment by skarllot** [comment]
> My initial gut reaction is "just compose Somes + Map, FP embraces composition", but on the other, Sequence is often provided as a shorthand for Traverse(x => x), so I think we can add an overload with a selector. I'd just be concerned that the name Choose wouldn't convey the meaning of what it does, and Somes(x => x.Property) also feels a bit weird.

I agree about about composition, `Somes` + `Map` seems better.

> We purposely have been using IReadOnlyList as the default list interface because in practice, more often than not we would get a Possible multiple enumeration﻿ warning and would then have to enumerate to a temporary variable. Also, for certain operations like Map, we can pre-allocate a list with a known size ahead of time.

I think that, in this case, should call `ToList` explicitly.

> On the other hand, as I assume is your point, this does mean using eager evaluation which may also not be desirable. In those cases, what we've done is define 2 overloads, one that accepts and returns IEnumerable and one that accepts and returns IReadOnlyList. The compiler will choose the more specialized one, so we get the benefit of both.

I agree, fits better in case of chaining with `Map` or `FirstOrNone`, for example.

**Comment by skarllot** [comment]
> EDIT: Perhaps SomesMap for the name of the overload with the selector?

Feels good too

**Comment by jeffijoe** [comment]
> I think that, in this case, should call ToList explicitly.

Yes, that's what we had to do with a temporary variable which got annoying when we accept `IEnumerable` as a parameter but the implementation 9/10 times need to enumerate to a list, so we decided to use `IReadOnlyList` as the default and then add overloads for `IEnumerable` when there is a performance win.

So with that in mind, I would suggest the following:

* Add `SomesMap` with 2 overloads: one for `IEnumerable` and one for `IReadOnlyList` - the latter can call the former by casting the input to `(IEnumerable<Option<T>>)source` and call `ToList` on the result since in this case there's no benefit to pre-allocating a list.
* Refactor `Somes` to have the same 2 overloads, each with a specific implementation optimized for their use case.

**Comment by skarllot** [comment]
The `GenerateTransformer` attribute is being effective for the `Somes` method?

**Comment by jeffijoe** [comment]
Yes it is. I just remembered that because the transformer generator generates overloads, it will probably generate one too many and therefore not compile.

Until we fix that, I think we should go with the `IReadOnlyList`-returning implementation for now since it'll be generator-friendly.

**Comment by skarllot** [comment]
It is compiling here, no problems

**Comment by jeffijoe** [comment]
With both overloads having the `GenerateTransformer`?

**Comment by skarllot** [comment]
> With both overloads having the `GenerateTransformer`?

Yes

**Comment by jeffijoe** [comment]
Nice, in that case carry on 😄

**Comment by skarllot** [comment]
> Add SomesMap with 2 overloads: one for IEnumerable and one for IReadOnlyList - the latter can call the former by casting the input to (IEnumerable<Option<T>>)source and call ToList on the result since in this case there's no benefit to pre-allocating a list.

Why you think that there's no benefit for pre-allocating for `SomesMap` but does for `Somes`?

**Comment by jeffijoe** [comment]
You're right, I forgot that in `Somes` we pre-allocate as well, so feel free to copy that for the `SomesMap` that returns a list. 👍

**Comment by skarllot** [comment]
Should generate transformer for `SomesMap`?

**Comment by jeffijoe** [comment]
Yes if it works, otherwise don't bother with it.

**Comment by skarllot** [comment]
@jeffijoe code updated

**Pull request merged**
